version: "3.8"
services:
  brain:
    build:
      context: .
      dockerfile: Dockerfile.brain.dev
    container_name: brain
    volumes:
      - .:/app
    environment:
      - NETWORK=mainnet
      - _DAPPNODE_CONSENSUS_CLIENT_MAINNET=prysm.dnp.dappnode.eth
      - _DAPPNODE_EXECUTION_CLIENT_MAINNET_VERSION=geth.dnp.dappnode.eth
    networks:
      dncore_network:
        aliases:
          - brain.web3signer.dappnode
  signer:
    image: consensys/web3signer:latest
    depends_on:
      - db
    security_opt:
      - "seccomp:unconfined"
    container_name: signer
    command:
      [
        "--key-store-path=/keystores",
        "--http-listen-port=9000",
        "--http-listen-host=0.0.0.0",
        "--http-host-allowlist=validator.prysm.dappnode,brain.web3signer.dappnode",
        "--http-cors-origins=*",
        "--idle-connection-timeout-seconds=90",
        "eth2",
        "--network=mainnet",
        "--slashing-protection-db-url=jdbc:postgresql://postgres.web3signer.dappnode:5432/web3signer-mainnet",
        "--slashing-protection-db-username=postgres",
        "--slashing-protection-db-password=mainnet",
        "--key-manager-api-enabled=true",
      ]
    networks:
      dncore_network:
        aliases:
          - web3signer.web3signer.dappnode
  db:
    build:
      context: .
      dockerfile: Dockerfile.db.dev
      args:
        UPSTREAM_VERSION: 23.1.0
    container_name: signer-db
    command: postgres
    user: postgres
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      dncore_network:
        aliases:
          - postgres.web3signer.dappnode

  prysm-validator:
    image: gcr.io/prysmaticlabs/prysm/validator:latest
    container_name: prysm-validator
    command:
      [
        "--mainnet",
        "--datadir=/data",
        "--wallet-dir=/root/.eth2validators",
        "--beacon-rpc-provider=beacon-chain.prysm.dappnode:4000",
        "--beacon-rpc-gateway-provider=beacon-chain.prysm.dappnode:3500",
        "--validators-external-signer-url=http://web3signer.web3signer.dappnode:9000",
        "--grpc-gateway-host=0.0.0.0 ",
        "--grpc-gateway-port=3500",
        "--grpc-gateway-corsdomain=http://0.0.0.0:3500",
        "--graffiti=validating_from_DAppNode",
        "--suggested-fee-recipient=0x0000000000000000000000000000000000000000",
        "--web",
        "--accept-terms-of-use",
        "--enable-doppelganger",
      ]
    networks:
      dncore_network:
        aliases:
          - validator.prysm.dappnode

networks:
  dncore_network:
    external: true
