name: "Build and test"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.15.0

      # Build

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Build webpack
        run: yarn build:webpack

      # Test

      - name: Test
        run: yarn test
